### ISSUE TITLE
Zache#clean is broken?

### ISSUE THREAD

**Issue by jviney** [yegor256/zache#75]
https://github.com/yegor256/zache/blob/master/lib/zache.rb#L180 passes the value to `#expired?`, but it's expecting the key.

**Comment by yegor256** [comment]
@jviney most probably a bug. Can you please submit a pull request together with a unit test reproducing the issue? I will greatly appreciate it!

**Comment by miclast** [comment]
class Zache
  def clean
    synchronized { @hash.delete_if { |key, value| expired?(key) } }
  end
end

Fix for this bug.

**Comment by yegor256** [comment]
@rultor release, tag `0.13.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.2`

**Comment by yegor256** [comment]
@jviney should be resolved, try version 0.13.2
